#!/usr/bin/env python
#
#  This file is part of Etherwall
#  Copyright (C) Agus Bimantoro <l0g.bima@gmail.com>
#  This program is published under a GPLv3 license
#
#
#  Purpose: Display an active interface
#

import all

def main():
    iface   = all.get_if_conf()[0]
    hwaddr  = all.get_if_conf()[1]
    ipaddr  = all.get_if_conf()[2]
    gw      = all.get_if_conf()[3]
    mask   = all.get_if_conf()[4]
    cidr    = all.get_if_conf()[5]

    print ("\n---------------------------------------------------------------------------------------------")
    print ("%-17s%-20s%-17s%-17s%-17s%s" % ("Iface","HWaddr","IPaddr","Gateway","Netmask","CIDR"))
    print ("---------------------------------------------------------------------------------------------")
    print ("%-17s%-20s%-17s%-17s%-17s/%s" % (iface,hwaddr,ipaddr,gw,mask,cidr))
    print ("---------------------------------------------------------------------------------------------\n")
    
if __name__ == "__main__":
  try:
    main()
  except TypeError:
    print ("\n[!] No Devices Up\n")
  
## EOF ##
